<?xml version="1.0" encoding="UTF-8"?><testrun name="UserExchangeDispatcherSpec" project="restexchange_user_client" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.sysiq.restwebinars.user_client_spec.UserExchangeDispatcherSpec" time="0.993">
    <testcase name="testGetRate" classname="com.sysiq.restwebinars.user_client_spec.UserExchangeDispatcherSpec" time="0.993">
      <error>com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect&#13;
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)&#13;
	at com.sun.jersey.api.client.Client.handle(Client.java:652)&#13;
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)&#13;
	at com.sun.jersey.api.client.WebResource.get(WebResource.java:193)&#13;
	at com.sysiq.restwebinars.user_client.model.helpers.UserExchangeDispatcher.convertUSDToUAH(UserExchangeDispatcher.java:36)&#13;
	at com.sysiq.restwebinars.user_client_spec.UserExchangeDispatcherSpec.testGetRate(UserExchangeDispatcherSpec.java:24)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.net.ConnectException: Connection refused: connect&#13;
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)&#13;
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)&#13;
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)&#13;
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)&#13;
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.PlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.SocksSocketImpl.connect(Unknown Source)&#13;
	at java.net.Socket.connect(Unknown Source)&#13;
	at java.net.Socket.connect(Unknown Source)&#13;
	at sun.net.NetworkClient.doConnect(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.openServer(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.openServer(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.&lt;init&gt;(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.New(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.New(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)&#13;
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)&#13;
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:253)&#13;
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)&#13;
	... 29 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
